language: perl
perl:
    - 5.20
    - 5.18
    - 5.14

before_install:
    - cpanm http://backpan.perl.org/authors/id/M/MS/MSCHILLI/Log-Log4perl-1.44.tar.gz

notifications:
    email:
        on_success: never
        on_failure: never
